### PR TITLE
Eventide Intake

### PR DESCRIPTION
**Pull request by edennoelh**
@jaredh159 @Henderjay

### CODE REVIEW

**Comment by jaredh159** [comment]
PDF Previews for commit ce9a6ff:

* [649c46de--modernized--01-eventide.adoc](https://flp-assets.nyc3.digitaloceanspaces.com/actions/mary-ann-kelty/32/649c46de--modernized--01-eventide.adoc)
* [649c46de--original--01-eventide.adoc](https://flp-assets.nyc3.digitaloceanspaces.com/actions/mary-ann-kelty/32/649c46de--original--01-eventide.adoc)

**Comment by jaredh159** [comment]
@Henderjay and @edennoelh -- so the PDF previews are temporarily broken, due to a new version of Ubuntu that github actions has, that caused prince to be missing some shared C libraries.  i have a fix ready, and it should be that if you close this PR by merging it, and she re-starts a new task, the PDFs will work. but if she just keeps adding to this task, the pdfs will be broken. so if it doesn't cause a problem, she lets merge this one and re-open a new one. but if for some reason thats a problem, i can generate the pdfs manually, and link them, like i did in the above comment.

**Comment by jaredh159** [comment]
actually, i just realized, this might be the whole thing, maybe there is no other work. forgot this is all in one long chapter.

**Comment by Henderjay** [comment]
Hey Eden, this all looks good. I'm going to merge your PR, and have you open a new one in order to keep working on it. But I'd like you to tweak a couple things when you open up the new PR. 
1. I think the numbers of the daily devotionals should be centered. So go through and instead of putting (for example)
`=== 141`
you should put:
```
[.centered]
=== 141
```
Do this above all of the numbers 👍🏻 

Also... I think we should change the title of the preface from Advertisement. To the Reader.   to: Advertisement to the Reader (with no punctuation after it)

**Pull request merged**
